default-resources:
    - cpus=1
    - gpu="0"
    - mem_mb=512
    - runtime=5
restart-times: 0
printshellcmds: True
use-singularity: True
singularity-args: " --cleanenv --nv"
use-conda: True
conda-frontend: "mamba"
keep-going: True
rerun-incomplete: True
