ethics_prefix: "Merp11360_"

datadir: "/nesi/nobackup/uoa04027/dicom_mtay316"
resultsdir: "/nesi/nobackup/uoa04027/Processed_mtay316"

acqparams: "config/acqparams.txt"
index: "config/index.txt"
fs_license: "config/fs_license.txt"


heudiconv:
    heuristic: config/heuristic.py
    threads: 2
    mem_mb: 4000
    time_min: 60

mriqc:
    mem_mb: 16000
    time_min: 120
    threads: 8

synb0_disco:
    threads: 2
    mem_mb: 50000
    time_min: 300

hd_bet:
    extra_args: "-tta 0 -mode fast -device cpu"
    threads: 1
    mem_mb: 4000
    time_min: 20

denoise:
    threads: 2
    mem_mb: 2000
    time_min: 10

ringing_correction:
    threads: 2
    mem_mb: 2000
    time_min: 10

eddy:
    executable: "eddy_cuda10.2"  # support eddy_cuda10.2 or eddy_cpu
    extra_args: "--fwhm=0 --flm=quadratic --cnr_maps --repol --mporder=6 --residuals"
    threads: 2
    mem_mb: 4000
    time_min: 60
    gpu: "P100:1"
    slurm_extra: "--partition gpu"

eddy_quad:
    threads: 2
    mem_mb: 2000
    time_min: 30

eddy_squad:
    threads: 2
    mem_mb: 2000
    time_min: 30
