ethics_prefix: "Conc_20Ntb14_"
datadir: "/nesi/nobackup/uoa03264/dti_pipeline_data/dicom_max"
resultsdir: "/nesi/nobackup/uoa03264/dti_pipeline_data/processed_max"
fs_license: "fs_license.txt"

heudiconv:
    heuristic: config/heuristic.py
    threads: 2
    mem_mb: 4000
    time_min: 60

ringing_correction:
    threads: 2
    mem_mb: 2000
    time_min: 10
