ethics_prefix: "Conc_20Ntb14_"
datadir: "/nesi/nobackup/uoa03264/dti_pipeline_data/dicom_max"
resultsdir: "/nesi/nobackup/uoa03264/dti_pipeline_data/processed_max"

acqparams: "config/acqparams.txt"
fs_license: "config/fs_license.txt"

heudiconv:
    heuristic: config/heuristic.py
    threads: 2
    mem_mb: 4000
    time_min: 60

synb0_disco:
    threads: 2
    mem_mb: 50000
    time_min: 300

hd_bet:
    threads: 1
    mem_mb: 4000
    time_min: 20

denoise:
    threads: 2
    mem_mb: 2000
    time_min: 10

ringing_correction:
    threads: 2
    mem_mb: 2000
    time_min: 10

eddy:
    index: config/index.txt
    threads: 2
    mem_mb: 4000
    time_min: 30
    gpu: "P100:1"
    slurm_extra: "--partition gpu"
